<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAneguxu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAneguxu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAneguxu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAneguxu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAneguxu\appProdProjectContainer([
    'container.build_hash' => 'Aneguxu',
    'container.build_id' => '04f444e5',
    'container.build_time' => 1554187468,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAneguxu');
