<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF66kh71\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF66kh71/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerF66kh71.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerF66kh71\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerF66kh71\appProdProjectContainer([
    'container.build_hash' => 'F66kh71',
    'container.build_id' => '2f002932',
    'container.build_time' => 1554101281,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF66kh71');
