<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGwyktcn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGwyktcn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGwyktcn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGwyktcn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGwyktcn\appProdProjectContainer([
    'container.build_hash' => 'Gwyktcn',
    'container.build_id' => '8e49ad06',
    'container.build_time' => 1552297122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGwyktcn');
