<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMjmvj0c\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMjmvj0c/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMjmvj0c.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMjmvj0c\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMjmvj0c\appProdProjectContainer([
    'container.build_hash' => 'Mjmvj0c',
    'container.build_id' => '2d9c6c0b',
    'container.build_time' => 1557475503,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMjmvj0c');
